// JavaScript Document
$(document).ready(function() {
	$("#one").click(function(){
		$(this).css({"background":"#2dae00"});
		$("#twe").css({"background":"#b4b4b4"});
		$("#three").css({"background":"#b4b4b4"});
		$("#four").css({"background":"#b4b4b4"});
		$(".right_0").show();
		$(".right_2").hide();
		$(".right_3").hide();
		$(".right_1").hide();
	})
	$("#twe").click(function(){
		$(this).css({"background":"#2dae00"});
		$("#one").css({"background":"#b4b4b4"});
		$("#three").css({"background":"#b4b4b4"});
		$("#four").css({"background":"#b4b4b4"});
		$(".right_1").show();
		$(".right_2").hide();
		$(".right_3").hide();
		$(".right_0").hide();
	})
	$("#three").click(function(){
		$(this).css({"background":"#2dae00"});
		$("#twe").css({"background":"#b4b4b4"});
		$("#one").css({"background":"#b4b4b4"});
		$("#four").css({"background":"#b4b4b4"});
		$(".right_2").show();
		$(".right_3").hide();
		$(".right_1").hide();
		$(".right_0").hide();
	})
	$("#four").click(function(){
		$(this).css({"background":"#2dae00"});
		$("#twe").css({"background":"#b4b4b4"});
		$("#one").css({"background":"#b4b4b4"});
		$("#three").css({"background":"#b4b4b4"});
		$(".right_3").show();
		$(".right_2").hide();
		$(".right_1").hide();
		$(".right_0").hide();
	})
});